### ISSUE TITLE
    ../bin/templer archetype mycompanyid.content fails: ERROR: No egg-info directory found

### ISSUE THREAD

**Issue by miohtama** [collective/templer.plone#2]
Here is a full traceback::

```
../bin/templer archetype mycompanyid.content

archetype: A Plone project that uses Archetypes content types

This creates a Plone add-on package with the required infrastructure
to create custom Archetypes content types.

This template supports local commands.  These commands allow you to
generate skeleton content types and add fields and other features to
your new types.


If at any point, you need additional help for a question, you can enter
'?' and press RETURN.

Expert Mode? (What question mode would you like? (easy/expert/all)?) ['easy']: 
Project Title (Title of the project) ['Example Name']: Test
Version (Version number for project) ['1.0']: 1.0
Description (One-line description of the project) ['']: 
Creating directory ./mycompanyid.content
Replace 70 bytes with 42 bytes (3/6 lines changed; 1 lines removed)
Replace 895 bytes with 1231 bytes (5/32 lines changed; 16 lines added)

**************************************************************************
**  Your new package supports local commands.  To access them, change
**  directories into the 'src' directory inside your new package.
**  From there, you will be able to run the command `paster add
**  --list` to see the local commands available for this package.
**************************************************************************

Replace 1231 bytes with 1878 bytes (15/48 lines changed; 23 lines added)
Replace 119 bytes with 2078 bytes (2/5 lines changed; 45 lines added)
Replace 632 bytes with 830 bytes (5/19 lines changed; 7 lines added)
Replace 71 bytes with 71 bytes (1/4 lines changed)
Replace 1 bytes with 2 bytes (0/1 lines changed)
------------------------------------------------------------------------------
The project you just created has local commands. These can be used from within
the product.

usage: paster COMMAND

Commands:
  add  Allows the addition of further templates to an existing package

For more information: paster help COMMAND
------------------------------------------------------------------------------

**************************************************************************
**  Your new package supports local commands.  To access them, change
**  directories into the 'src' directory inside your new package.
**  From there, you will be able to run the command `paster add
**  --list` to see the local commands available for this package.
**************************************************************************


ERROR: No egg-info directory found (looked in ./mycompanyid.content/./mycompanyid.content.egg-info, ./mycompanyid.content/bootstrap.py/mycompanyid.content.egg-info, ./mycompanyid.content/buildout.cfg/mycompanyid.content.egg-info, ./mycompanyid.content/CHANGES.txt/mycompanyid.content.egg-info, ./mycompanyid.content/CONTRIBUTORS.txt/mycompanyid.content.egg-info, ./mycompanyid.content/docs/mycompanyid.content.egg-info, ./mycompanyid.content/MANIFEST.in/mycompanyid.content.egg-info, ./mycompanyid.content/mycompanyid/mycompanyid.content.egg-info, ./mycompanyid.content/README.txt/mycompanyid.content.egg-info, ./mycompanyid.content/setup.cfg/mycompanyid.content.egg-info, ./mycompanyid.content/setup.py/mycompanyid.content.egg-info, ./mycompanyid.content/src/mycompanyid.content.egg-info)
```

**Comment by cewing** [comment]
Mikko,

Is this from running the initial template run, or from trying a local command?

If you are getting it for the initial template run, I've seen an error like that on occasion.  It happens most often on Windows, but I have seen it on OS X too. I have not managed to figure out why it is raised sometimes but not others.  It doesn't appear to affect the outcome of the actual process.  In other words, the created package should still be fine.  A bottle of your favorite beverage if you can figure out why it is happening.

If you are seeing it when running a local command, it's because you aren't in the 'src' directory of your new package when you run the local command.  The paster code that finds setup.cfg to figure out what template was originally run is brain-dead and requires finding egg-info first.  It looks in the current directory and moves upwards, but if you are not in the same directory as .egg-info or below it, it won't be found and you'll see that error.

c

On Jul 10, 2012, at 10:22 AM, Mikko Ohtamaa wrote:

> Here is a full traceback::
> 
>    ../bin/templer archetype mycompanyid.content
> 
>    archetype: A Plone project that uses Archetypes content types
> 
>    This creates a Plone add-on package with the required infrastructure
>    to create custom Archetypes content types.
> 
>    This template supports local commands.  These commands allow you to
>    generate skeleton content types and add fields and other features to
>    your new types.
> 
>    If at any point, you need additional help for a question, you can enter
>    '?' and press RETURN.
> 
>    Expert Mode? (What question mode would you like? (easy/expert/all)?) ['easy']: 
>    Project Title (Title of the project) ['Example Name']: Test
>    Version (Version number for project) ['1.0']: 1.0
>    Description (One-line description of the project) ['']: 
>    Creating directory ./mycompanyid.content
>    Replace 70 bytes with 42 bytes (3/6 lines changed; 1 lines removed)
>    Replace 895 bytes with 1231 bytes (5/32 lines changed; 16 lines added)
> 
> ---
> 
>    *\*  Your new package supports local commands.  To access them, change
>    *\*  directories into the 'src' directory inside your new package.
>    *\*  From there, you will be able to run the command `paster add
>    **  --list` to see the local commands available for this package.
> 
> ---
> 
>    Replace 1231 bytes with 1878 bytes (15/48 lines changed; 23 lines added)
>    Replace 119 bytes with 2078 bytes (2/5 lines changed; 45 lines added)
>    Replace 632 bytes with 830 bytes (5/19 lines changed; 7 lines added)
>    Replace 71 bytes with 71 bytes (1/4 lines changed)
>    Replace 1 bytes with 2 bytes (0/1 lines changed)
> 
> ---
> 
>    The project you just created has local commands. These can be used from within
>    the product.
> 
>    usage: paster COMMAND
> 
>    Commands:
>      add  Allows the addition of further templates to an existing package
> 
>    For more information: paster help COMMAND
> 
> ---
> 
> ---
> 
>    *\*  Your new package supports local commands.  To access them, change
>    *\*  directories into the 'src' directory inside your new package.
>    *\*  From there, you will be able to run the command `paster add
>    **  --list` to see the local commands available for this package.
> 
> ---
> 
>    ERROR: No egg-info directory found (looked in ./mycompanyid.content/./mycompanyid.content.egg-info, ./mycompanyid.content/bootstrap.py/mycompanyid.content.egg-info, ./mycompanyid.content/buildout.cfg/mycompanyid.content.egg-info, ./mycompanyid.content/CHANGES.txt/mycompanyid.content.egg-info, ./mycompanyid.content/CONTRIBUTORS.txt/mycompanyid.content.egg-info, ./mycompanyid.content/docs/mycompanyid.content.egg-info, ./mycompanyid.content/MANIFEST.in/mycompanyid.content.egg-info, ./mycompanyid.content/mycompanyid/mycompanyid.content.egg-info, ./mycompanyid.content/README.txt/mycompanyid.content.egg-info, ./mycompanyid.content/setup.cfg/mycompanyid.content.egg-info, ./mycompanyid.content/setup.py/mycompanyid.content.egg-info, ./mycompanyid.content/src/mycompanyid.content.egg-info)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/collective/templer.plone/issues/2

## Cris Ewing

Principal, Cris Ewing, Developer LLC
http://www.crisewing.com
cris@crisewing.com
1.206.724.2112

**Comment by miohtama** [comment]
Initial run (as seen in the full log).

Local commands are not available. Should they be enabled to archetypes template and how?

**Comment by miohtama** [comment]
What I get is:

```
[/fast/sits3/src/mycompanyid.content]% ../../bin/paster addcontent
Command 'addcontent' not known (you may need to run setup.py egg_info)
Known commands:
  create       Create the file layout for a Python distribution
  exe          Run #! executable files
  help         Display help
  make-config  Install a package and create a fresh config file/directory
  points       Show information about entry points
  post         Run a request for the described application
  request      Run a request for the described application
  serve        Serve the described application
  setup-app    Setup an application, given a config file
```

(no addcontent)

Related?

**Comment by miohtama** [comment]
There is  paster_plugins=["templer.localcommands"] in setup.py but no templer.plone.localcommands

**Comment by cewing** [comment]
did you pip install?  If so, upgrade to the most recent pip.  Earlier version did not support proper installation of 'extras'.  The current version does

c

On Jul 10, 2012, at 11:21 AM, Mikko Ohtamaa wrote:

> There is  paster_plugins=["templer.localcommands"] in setup.py but no templer.plone.localcommands
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/collective/templer.plone/issues/2#issuecomment-6884116

## Cris Ewing

Principal, Cris Ewing, Developer LLC
http://www.crisewing.com
cris@crisewing.com
1.206.724.2112

**Comment by cewing** [comment]
possibly related.  More likely related to your next email about templer.plone.localcommands being missing.  But the command is now 'add', not 'addcontent'.  Renamed because the old name was content-centric, but the command can add content, schema, fields, and all sorts of other stuff

c

On Jul 10, 2012, at 11:20 AM, Mikko Ohtamaa wrote:

> What I get is:
> 
>    [/fast/sits3/src/mycompanyid.content]% ../../bin/paster addcontent
>    Command 'addcontent' not known (you may need to run setup.py egg_info)
>    Known commands:
>      create       Create the file layout for a Python distribution
>      exe          Run #! executable files
>      help         Display help
>      make-config  Install a package and create a fresh config file/directory
>      points       Show information about entry points
>      post         Run a request for the described application
>      request      Run a request for the described application
>      serve        Serve the described application
>      setup-app    Setup an application, given a config file
> 
> (no addcontent)
> 
> Related?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/collective/templer.plone/issues/2#issuecomment-6884095

## Cris Ewing

Principal, Cris Ewing, Developer LLC
http://www.crisewing.com
cris@crisewing.com
1.206.724.2112

**Comment by miohtama** [comment]
Ok. I think I have found the error causing this, comes from the buildout... more info soon.

**Comment by miohtama** [comment]
It does not work:

```
  Running /Users/moo/code/python/python-2.6/bin/python setup.py egg_info
  Traceback (most recent call last):
    File "../bin/paster", line 23, in <module>
      paste.script.command.run()
    File "/fast/sits3/src/sits-packages/sits.download/PasteScript-1.7.5-py2.6.egg/paste/script/command.py", line 104, in run
      invoke(command, command_name, options, args[1:])
    File "/fast/sits3/src/sits-packages/sits.download/PasteScript-1.7.5-py2.6.egg/paste/script/command.py", line 143, in invoke
      exit_code = runner.run(args)
    File "/fast/sits3/src/sits-packages/sits.download/PasteScript-1.7.5-py2.6.egg/paste/script/command.py", line 238, in run
      result = self.command()
    File "/fast/sits3/src/sits-packages/sits.download/PasteScript-1.7.5-py2.6.egg/paste/script/create_distro.py", line 170, in command
      egg_info_dir = pluginlib.egg_info_dir(output_dir, dist_name)
    File "/fast/sits3/src/sits-packages/sits.download/PasteScript-1.7.5-py2.6.egg/paste/script/pluginlib.py", line 135, in egg_info_dir
      % ', '.join(all))
  IOError: No egg-info directory found (looked in ./mycompany.content/./mycompany.content.egg-info, ./mycompany.content/bootstrap.py/mycompany.content.egg-info, ./mycompany.content/buildout.cfg/mycompany.content.egg-info, ./mycompany.content/CHANGES.txt/mycompany.content.egg-info, ./mycompany.content/CONTRIBUTORS.txt/mycompany.content.egg-info, ./mycompany.content/docs/mycompany.content.egg-info, ./mycompany.content/MANIFEST.in/mycompany.content.egg-info, ./mycompany.content/mycompany/mycompany.content.egg-info, ./mycompany.content/Paste-1.7.5.1-py2.6.egg/mycompany.content.egg-info, ./mycompany.content/PasteDeploy-1.5.0-py2.6.egg/mycompany.content.egg-info, ./mycompany.content/PasteScript-1.7.5-py2.6.egg/mycompany.content.egg-info, ./mycompany.content/README.txt/mycompany.content.egg-info, ./mycompany.content/setup.cfg/mycompany.content.egg-info, ./mycompany.content/setup.py/mycompany.content.egg-info, ./mycompany.content/src/mycompany.content.egg-info)
```

Looks the generated folder structure is somehow broken:

Gets created (obviously broken - which could generate them):

```
    ./mycompany
    ./mycompany/__init__.py
    ./mycompany/content
    ./mycompany/content/__init__.py
```

Also gets created:

```
      ./src
      ./src/mycompany
      ./src/mycompany/content
      ./src/mycompany/content/__init__.py
      ./src/mycompany/content/browser
      ./src/mycompany/content/browser/__init__.py
      ./src/mycompany/content/browser/configure.zcml
      ./src/mycompany/content/config.py
      ./src/mycompany/content/configure.zcml
      ./src/mycompany/content/content
      ./src/mycompany/content/content/__init__.py
      ./src/mycompany/content/content/configure.zcml
```

Running paster create and templer both yield to the same result, so the problem lies in templates somehow.

**Comment by cewing** [comment]
I am seeing nothing like this locally.  Is it possible that you have conflicting copies of the archetypes package templates?  I have seen output with that dual top-level structure in ZopeSkel installations, but never in a templer installation.  Can you try isolating things by setting up a completely clean virtualenv?  

The double structure would certainly explain the prroblem in generating the egg-info directory.  And that failure would explain pretty much all the other behaviors you see.

**Comment by miohtama** [comment]
Ok found the error. Old ZopeSkel was coexisting in the same buildout.
